### ISSUE TITLE
Add Binary APK Release Action

### ISSUE THREAD

**Issue by canewsin** [KodeSaiRatnakar/whatsappclone#1]
Code
```
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
```
More Info at https://github.com/actions/upload-artifact.git
